/**
 * Public roadmap with voting.
 *
 * Curated list of items in three buckets: planned, in-progress,
 * shipped. Each item has a stable id (slug), a title, a short
 * description, and a vote counter.
 *
 * GET  /api/roadmap                — { items: [...] } with current counts
 * POST /api/roadmap/vote { itemId } — one vote per browser per item
 *
 * Voting auth: client provides a stable fingerprint (random uuid
 * generated by the browser and stored in cookie 'cybersygn_voter').
 * We dedupe in KV under `roadmap-vote:<itemId>:<voter>`.
 *
 * No PII collected. The voter is a random ID generated client-side,
 * no IP, no email. The fact that votes are deduped per browser is
 * good enough for a sentiment signal.
 */

const ITEMS = [
  // Planned (top of the list)
  { id: 'co-sign-durable-objects', status: 'planned', title: 'Co-signing on websockets', desc: 'Upgrade presence + live fills from polling to Durable Object websockets so both signers see each others typing in real time.' },
  { id: 'mobile-pwa', status: 'planned', title: 'Mobile PWA install', desc: 'Add-to-home-screen prompt + offline shell so signers can sign documents without an open tab.' },
  { id: 'zapier', status: 'planned', title: 'Zapier integration', desc: 'Trigger on signed-document, action on send-document. Plug CyberSygn into any CRM, ATS, or HR stack.' },
  { id: 'sso-studio', status: 'planned', title: 'Google + Microsoft SSO', desc: 'Studio tier login via Workspace and Entra so teams stop sharing senderId tokens.' },
  { id: 'audit-log-search', status: 'planned', title: 'Audit log search', desc: 'Searchable history of every send and every signature on /dashboard/ for power users.' },
  { id: 'custom-domains', status: 'planned', title: 'Custom signing domains', desc: 'Send signers to sign.your-firm.com instead of cybersygn.io. Studio tier.' },
  { id: 'voice-annotation', status: 'planned', title: 'Voice annotation', desc: 'Attach a 30-second voice note to any signed document. Surfaces in the audit cert.' },
  { id: 'mobile-biometric', status: 'planned', title: 'Biometric signing', desc: 'Face ID and Touch ID confirmation on signing submit for repeat mobile signers.' },

  // In progress
  { id: 'affiliate-payouts', status: 'in-progress', title: 'Automated affiliate payouts', desc: 'Auto-debit Stripe Connect every month for affiliate balances above $20.' },
  { id: 'bulk-send-templates', status: 'in-progress', title: 'Bulk send + templates', desc: 'When a template is saved for a doc, bulk send auto-applies it to every recipient. Zero re-detection.' },

  // Shipped (recent first)
  { id: 'co-signing-presence', status: 'shipped', title: 'Co-signing presence', desc: 'See where every signer is in the document in real time. Slice 86.' },
  { id: 'bulk-send-ui', status: 'shipped', title: 'Bulk send (UI)', desc: '/dashboard/bulk-send/. PDF + CSV → 200 personalized magic links. Slice 85.' },
  { id: 'affiliate-dashboard', status: 'shipped', title: 'Affiliate program', desc: '$20 per converted referral. Visible on /dashboard/. Slice 76 + 84.' },
  { id: 'embed-widget', status: 'shipped', title: 'Embed widget', desc: 'Two lines of HTML embeds the signing flow on any site. Slice 78.' },
  { id: 'mobile-sheet', status: 'shipped', title: 'Mobile bottom-sheet UX', desc: 'Phone signing redesigned around thumb reachability. Slice 79.' },
  { id: 'signer-microsite', status: 'shipped', title: 'Signer microsite', desc: 'Magic-link signers see a post-submit "want your own account?" wedge. Slice 75.' },
  { id: 'viral-footer', status: 'shipped', title: 'Viral PDF footer', desc: 'Every signed PDF carries a discreet "Signed with CyberSygn" link. Slice 74.' },
  { id: 'detect-100', status: 'shipped', title: '100% detection on 37 contracts', desc: 'Regression set passes 37 of 37 real-world contracts + 10 of 10 synthetic.' },
  { id: 'origin-tier', status: 'shipped', title: 'Origin tier (Charter 100)', desc: '$9/mo locked for the life of your account. Capped at 100 founders.' },
  { id: 'audit-cert', status: 'shipped', title: 'Audit certificate', desc: 'SHA-256 fingerprint, every signing event, IP + timestamp. Built in.' },
];

const PREFIX_VOTE = 'roadmap-vote:';
const PREFIX_COUNT = 'roadmap-count:';

export async function getRoadmap(env) {
  // Pull counts from KV (each item's counter lives at roadmap-count:<id>).
  // Cheap: 18 reads. We could collapse to a single JSON blob if it
  // becomes a hotspot, but right now this is fine.
  const counts = {};
  if (env && env.CYBERSYGN_DOCS) {
    await Promise.all(ITEMS.map(async item => {
      try {
        const raw = await env.CYBERSYGN_DOCS.get(PREFIX_COUNT + item.id);
        counts[item.id] = parseInt(raw, 10) || 0;
      } catch (e) { counts[item.id] = 0; }
    }));
  }
  return {
    items: ITEMS.map(it => ({ ...it, votes: counts[it.id] || 0 })),
  };
}

export async function castVote(env, itemId, voter) {
  if (typeof itemId !== 'string' || !ITEMS.find(i => i.id === itemId)) {
    return { ok: false, error: 'unknown_item' };
  }
  if (typeof voter !== 'string' || !/^[a-z0-9-]{8,64}$/.test(voter)) {
    return { ok: false, error: 'invalid_voter' };
  }
  if (!env || !env.CYBERSYGN_DOCS) return { ok: false, error: 'kv_unavailable' };

  const dedupeKey = PREFIX_VOTE + itemId + ':' + voter;
  try {
    const seen = await env.CYBERSYGN_DOCS.get(dedupeKey);
    if (seen) return { ok: true, alreadyVoted: true };
  } catch (e) {}
  // Mark voted + bump counter.
  const countKey = PREFIX_COUNT + itemId;
  let next = 1;
  try {
    const raw = await env.CYBERSYGN_DOCS.get(countKey);
    next = (parseInt(raw, 10) || 0) + 1;
    await env.CYBERSYGN_DOCS.put(countKey, String(next));
    await env.CYBERSYGN_DOCS.put(dedupeKey, '1', { expirationTtl: 60 * 60 * 24 * 365 * 5 });
  } catch (e) {}
  return { ok: true, votes: next };
}

export const __forTests = { ITEMS };
