#!/usr/bin/env node
/**
 * CyberSygn vendor script.
 *
 * Copies third-party runtime dependencies (pdf.js and the typeface
 * woff2 files) out of node_modules and into web/vendor/, then writes
 * a fonts.css file with the @font-face declarations.
 *
 * After this runs, the dev server and the production build both serve
 * the same self-hosted assets, and the deployed site has zero runtime
 * calls to third-party CDNs.
 *
 * Idempotent. Safe to rerun.
 */

import { readFile, writeFile, mkdir, rm, copyFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const NODE_MODULES = join(ROOT, 'node_modules');
const VENDOR = join(ROOT, 'web', 'vendor');
const VENDOR_FONTS = join(VENDOR, 'fonts');

// Curated weights only. Each woff2 is roughly 50-100 KB; we ship only
// what the design uses.
const FONT_SPECS = [
  { family: 'Fraunces', pkg: 'fraunces', weights: [400, 500, 600] },
  { family: 'Inter', pkg: 'inter', weights: [300, 400, 500, 600, 700] },
  { family: 'JetBrains Mono', pkg: 'jetbrains-mono', weights: [400, 500] },
];

const PDFJS_FILES = [
  { src: 'pdfjs-dist/legacy/build/pdf.mjs', dest: 'pdf.mjs' },
  { src: 'pdfjs-dist/legacy/build/pdf.worker.mjs', dest: 'pdf.worker.mjs' },
];

// pdf-lib: used by signing capture to embed signature bitmaps and
// flatten dates and checkmarks back into the original PDF.
const PDFLIB_FILES = [
  { src: 'pdf-lib/dist/pdf-lib.esm.min.js', dest: 'pdf-lib.mjs' },
];

// mammoth: lazy-loaded browser build for .docx ingestion. Only fetched
// when the user uploads a Word document, so PDF-only sessions pay zero
// bytes for it. Vendored under the same self-hosting principle as
// pdf.js and pdf-lib.
const MAMMOTH_FILES = [
  { src: 'mammoth/mammoth.browser.min.js', dest: 'mammoth.browser.min.js' },
];

async function main() {
  console.log('CyberSygn vendor');
  console.log('  target:', VENDOR);
  console.log('');

  await rm(VENDOR, { recursive: true, force: true });
  await mkdir(VENDOR_FONTS, { recursive: true });

  // 1. pdf.js
  for (const f of PDFJS_FILES) {
    await copyFile(join(NODE_MODULES, f.src), join(VENDOR, f.dest));
    console.log(`  pdfjs: ${f.dest}`);
  }

  // 2. pdf-lib (signing flatten)
  for (const f of PDFLIB_FILES) {
    await copyFile(join(NODE_MODULES, f.src), join(VENDOR, f.dest));
    console.log(`  pdf-lib: ${f.dest}`);
  }

  // 3. mammoth (docx ingestion)
  for (const f of MAMMOTH_FILES) {
    await copyFile(join(NODE_MODULES, f.src), join(VENDOR, f.dest));
    console.log(`  mammoth: ${f.dest}`);
  }

  // 2. Fonts: copy each weight's latin woff2 and generate @font-face.
  const faceRules = [];
  for (const spec of FONT_SPECS) {
    for (const weight of spec.weights) {
      const file = `${spec.pkg}-latin-${weight}-normal.woff2`;
      const src = join(NODE_MODULES, '@fontsource', spec.pkg, 'files', file);
      const dest = join(VENDOR_FONTS, file);
      await copyFile(src, dest);
      console.log(`  font: ${file}`);
      faceRules.push(
        `@font-face {\n` +
        `  font-family: "${spec.family}";\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url("./fonts/${file}") format("woff2");\n` +
        `}`,
      );
    }
  }

  const fontsCss =
    '/* Generated by scripts/vendor.js. Do not edit by hand. */\n' +
    faceRules.join('\n\n') + '\n';
  await writeFile(join(VENDOR, 'fonts.css'), fontsCss);
  console.log('  wrote fonts.css with', faceRules.length, '@font-face rules');

  console.log('');
  console.log('Vendor populated. Total weights:', faceRules.length);
}

main().catch(err => {
  console.error('vendor failed:', err);
  process.exit(1);
});
